### ISSUE TITLE
List dependency libargtable2-dev

### ISSUE THREAD

**Issue by harryhaaren** [jeremysalwen/lv2file#1]
Hi Jeremy,

A quick note that `libargtable2-dev` should probably be listed as an external dependency of lv2file.

Thanks for making this - I'm using it with valgrind to test plugins :) -Harry

**Comment by jeremysalwen** [comment]
Hi Harry,

I checked the debian packaging info, it looks like it depends on a few more:

> Build-Depends:
>  debhelper (>= 7.0.50~),
>  libargtable2-dev,
>  liblilv-dev,
>  libsndfile-dev,
>  lv2-dev

I'll add them to the readme.

Thanks for the feedback!
Jeremy

**Comment by harryhaaren** [comment]
Awesome thanks - I was missing only that package - hence I spotted only that one. Good choice to check the package info!

Thanks again, -Harry

**Comment by jeremysalwen** [comment]
Done.
